name: SnakeGame Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:   # <- 必须有 jobs
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug
        run: echo "Workflow is running"
